server:
  port: 8888        # 服务端口

# Spring配置
spring:
  application:
    name: edu       # 服务名，给SpringCloud使用
  # 环境设置：dev、test、prod
  profiles:
    active: dev     # 环境设置
  # MySQL数据库连接
  datasource:
    url: jdbc:mysql://localhost:3316/olympians?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: zeus
    password: yy123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名（since 3.3.0，配置后实体bean类可以不配置@TableLogic注解）
      logic-delete-value: 1       # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0   # 逻辑未删除值（默认为0）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # Mybatis日志