server:
  port: 8888        # 服务端口

# Spring配置
spring:
  application:
    name: edu       # 服务名，给SpringCloud使用
  # 环境设置：dev、test、prod
  profiles:
    active: dev     # 环境设置
  # MySQL数据库连接
  datasource:
    url: jdbc:mysql://localhost:3316/olympians?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
    username: zeus
    password: yy123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      # Failed to start bean 'documentationPluginsBootstrapper' in spring data rest
      # springfox3.0.0 has compatibility problem with spring boot 2.6.x
      matching-strategy: ant_path_matcher # to resolve spring fox null pointer problem



mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名（since 3.3.0，配置后实体bean类可以不配置@TableLogic注解）
      logic-delete-value: 1       # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0   # 逻辑未删除值（默认为0）
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # Mybatis日志


# ===== 自定义swagger配置 ===== #
swagger:
  enable: true     # 配置是否启用Swagger
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
  group-name: edu